# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: esolang/tetris:latest
  template:
    metadata:
      labels:
        app: esolang/tetris:latest
    spec:
      containers:
        - name: tetris
          image: esolang/tetris:latest # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
